# From https://github.com/sphinx-notes/pages
name: Build and push docs to gh-pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Docs dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-docs.txt ]; then pip install -r requirements-docs.txt; fi
        sudo apt install python-sphinx make
    - name: Build docs
      run: |
        cd docs/
        make html
        cd ..
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
