name: Package Application with Pyinstaller

on:
  push:
    branches: [master, release]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: "3.6"

    - run: pip install py2exe && python setup.py install

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: src/dist/windows
